import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import mainBanner from "../../public/images/main-banner.gif";
import AnimetedText from "@/components/AnimetedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Functions from "@/components/Functions";
import Tos from "@/components/Tos";
import TransitionEffect from "@/components/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AutoFriends | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center w-full min-h-screen text-dark">
        <Layout className="pt-0 md:p-16 sm:pt-8 ">
          <div className="flex items-center justify-between w-full my-48 lg:flex-col">
            <div className="flex flex-col self-center w-1/2 item-center lg:w-full lg:text-center">
              <AnimetedText
                text={"What is AutoFriends ?"}
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Autofriends is a free tool designed to make things easier on
                Facebook. It exists as a browser extension. We think this will
                be very useful for Facebook marketers
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  href={
                    "https://chrome.google.com/webstore/detail/autofriends/pmpbhhdmaaccngiofnbaelglocmabnae?hl=en-US&authuser=1"
                  }
                  target="_blank"
                  className="flex item-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base  "
                >
                  Download <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href={"https://wa.me/94767329082"}
                  target="_blank"
                  className="ml-4 text-lg font-medium underline capitalize text-dark md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
            <div className="w-1/2 md:w-full">
              <Image
                src={mainBanner}
                alt="robot"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
              />
            </div>
          </div>
          <Functions />
          <Tos />
        </Layout>
      </main>
    </>
  );
}
